import type { Metadata } from "next";
import { Calligraffitti } from 'next/font/google'
import "./globals.css";

const indieFlowe = Calligraffitti({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${indieFlowe.className}`}
      >
        {children}
      </body>
    </html>
  );
}
